### ISSUE TITLE
Events not working

### ISSUE THREAD

**Issue by Osmagtor** [5ony/OBSWebSocketAHK#9]
When subscribing to events I either get a "This value of type 'Object' has no property named '[insert field name]'" or nothing happens at all. I'm probably simply missing something very obvious, but I've gotten responses to work normally and I the README instructions are very straightforward. Here's an example script:

```
#Requires AutoHotkey v2.0
#Include OBSWebSocketAHK\OBSWebSocket.ahk

class MyOBSController extends OBSWebSocket {
	InputMuteStateChanged(data) {
		inputName := data.inputName
		inputMuted := data.inputMuted ? "muted 🔇" : "unmuted 🔊"
		MsgBox(inputName . " is now " . inputMuted)
	}
}

obsc := MyOBSController("ws://127.0.0.1:4455/", 0, MyOBSController.EventSubscription.Inputs | MyOBSController.EventSubscription.Scenes)

F12::MsgBox(obsc.IsWebSocketAlive())
```

**Comment by 5ony** [comment]
The received object has a bit different structure.
Check the part at Example Message [here](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#event-opcode-5)

If you change `data.*` to `data.d.eventData.*` (i.e. `data.inputName` to `data.d.eventData.inputName` etc), it should work.

That is for sure, I should refer to the original description about the event (or other) structure in this documentation as well. Thank you for your report!

**Comment by Osmagtor** [comment]
Now it works. Updating the documentation would indeed be a good idea. Thanks for you help!

**Comment by 5ony** [comment]
Funny thing is, every example were correct, except this one, the main example.
https://github.com/5ony/OBSWebSocketAHK/blob/main/README.md#-event-handling

Anyhow, this is a good sign that I should do a more friendly introduction to OBS AHK scripting, because I feel the documentation just goes deep into details, and the more relevant information just getting lost,

Thanks again for your feedback, and keep them coming! :)
